/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function YutAnimated({ props, ref }) {

}

useGLTF.preload("/yut-physics.glb");
