/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function NeptuneRay(props) {
  const { nodes, materials } = useGLTF("/neptune-ray.glb");
  return (
    <group
      {...props}
      position={props.position}
      dispose={null}
      scale={props.scale}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/neptune-ray.glb");
