/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function RocketUpright({position}) {
  const { nodes, materials } = useGLTF("/models/rocket-upright.glb");
  return (
    <group dispose={null} position={position} scale={0.2} rotation={[0, Math.PI/2, 0]}>
      <group
        position={[0.018, 2.81, 0.058]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={0.052}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle013.geometry}
          material={materials["Ship White"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle013_1.geometry}
          material={materials["Ship red"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle013_2.geometry}
          material={materials["Alien Black"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle034.geometry}
          material={materials["Ship red"]}
          position={[0.008, -48.617, 12.536]}
          rotation={[0.009, -1.571, 0]}
          scale={[1.225, 1.376, 1.225]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle036.geometry}
          material={materials["Ship red"]}
          position={[12.544, -48.617, 0]}
          rotation={[0, 0, -0.009]}
          scale={[1.225, 1.376, 1.225]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle037.geometry}
          material={materials["Ship red"]}
          position={[-6.703, -24.668, -6.925]}
          rotation={[0.806, -0.595, 2.119]}
          scale={18.152}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere002.geometry}
          material={materials.Fire}
          position={[0.008, -50.335, 0]}
          rotation={[0.024, 1.289, 0]}
          scale={3.393}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={materials["Ship red"]}
          position={[0.008, -43.911, 6.028]}
          rotation={[0.702, 0, Math.PI / 2]}
          scale={13.763}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={materials["Ship red"]}
          position={[6.036, -43.911, 0]}
          rotation={[Math.PI / 2, 0.869, 0]}
          scale={13.763}
        />
        <group
          position={[-7.273, -23.861, -7.749]}
          rotation={[2.849, -0.723, 2.936]}
          scale={[2.608, 2.608, 2.062]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roundcube023.geometry}
            material={materials["Astronaut red"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roundcube023_1.geometry}
            material={materials["Astro White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle038.geometry}
            material={materials["Astronaut red"]}
            position={[0.211, -1.383, 1.239]}
            rotation={[1.677, 0, 0]}
            scale={[0.126, 0.16, 0.127]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={nodes.Cube003.material}
            position={[0, -1.372, 1.1]}
            rotation={[0.106, 0, 0]}
            scale={[3.133, 3.143, 3.955]}
          />
          <group position={[0, 1.611, 0.398]} scale={[1.611, 1.611, 2.038]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roundcube021.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roundcube021_1.geometry}
              material={materials["Astro White"]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roundcube041.geometry}
            material={materials["Astro White"]}
            position={[1.485, 1.611, 0.398]}
            scale={[-0.303, -0.429, -0.543]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roundcube043.geometry}
            material={materials["Astro White"]}
            position={[0, -1.367, 0]}
            scale={0.977}
          />
          <group position={[0, -1.731, 0]} scale={[4.114, 4.114, 5.204]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roundcube025.geometry}
              material={materials["Astronaut red"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roundcube025_1.geometry}
              material={materials["Astro White"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Space Ship 05.glb");