/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RhinoConstellation(props) {
  const { nodes, materials } = useGLTF('models/rhino-constellation.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath030.geometry}
        material={materials['Material.019']}
        position={[-6.628, -0.437, -2.935]}
        rotation={[0, 0.746, 0]}
        scale={1.239}
      />
    </group>
  )
}

useGLTF.preload('models/rhino-constellation.glb')
