/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TaurusConstellation(props) {
  const { nodes, materials } = useGLTF('models/taurus-constellation.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Retopo_NurbsPath020.geometry}
        material={materials['Material.020']}
        position={[-1.475, -0.096, 0.449]}
        rotation={[0, 0.846, 0]}
        scale={0.067}
      />
    </group>
  )
}

useGLTF.preload('models/taurus-constellation.glb')