/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WolfConstellation(props) {
  const { nodes, materials } = useGLTF('models/wolf-constellation.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Retopo_NurbsPath009.geometry}
        material={materials['Material.020']}
        position={[-0.351, 0.025, -0.584]}
        rotation={[Math.PI, -1.274, Math.PI]}
        scale={0.048}
      />
    </group>
  )
}

useGLTF.preload('models/wolf-constellation.glb')
